spring:
  application:
    name: enteerprise-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_management_system
    username: springboottutorial
    password: springboottutorial
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: employee-service-connection-pool
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

account:
  transfer-amount:
    timeout: 1
