spring:
  application:
    name: multi-data-source
  datasource:
    employee:
      jdbc-url: jdbc:mysql://localhost:3306/employee_service
      username: springboottutorial
      password: springboottutorial
      driver-class-name: com.mysql.cj.jdbc.Driver

      hikari:
        pool-name: employee-db-connection-pool
        minimum-idle: 3
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        validation-timeout: 5000


    users:
      jdbc-url: jdbc:mysql://localhost:3306/user_database
      username: user1
      password: user1
      driver-class-name: com.mysql.cj.jdbc.Driver

      hikari:
        pool-name: user-db-connection-pool
        minimum-idle: 3
        maximum-pool-size: 5
        idle-timeout: 600000
        max-lifetime: 1800000
        connection-timeout: 30000
        validation-timeout: 5000
